Feature/activity class
megschuetz/fitlit pull request #25
Opened 2022-05-18 23:46 UTC by K-Howard

Add activity methods and more tests. Added more data sets to the test file for TDD.

2022-05-18 23:50 UTC, K-Howard commented
#### What's this PR do?
Adds activity methods and more tests as well as more data to test.
#### Where should the reviewer start?
Activity.js and activity-test
#### How should this be manually tested?
npm test
#### Any background context you want to provide?
Need another method or 2

#### Questions:
other things to test?

2022-05-19 00:14 UTC, ameliaeiger commented on README.md
> +
Needs a label for setup instructions

2022-05-19 00:15 UTC, megschuetz commented on test/Activity-test.js
> +//   });
Could leave any notes like out. Other than that looks good.

2022-05-19 00:18 UTC, ameliaeiger commented on README.md
> +### Demo of LitFit
FitLit

2022-05-19 16:31 UTC, ameliaeiger commented on src/user.js
> +class User {
I believe this is our file we were not using for user and which Megan had already deleted. Let's avoid re-adding this file to the repo.

2022-05-19 16:37 UTC, ameliaeiger requested changes
Let's avoid uploading the user.js file that Megan has deleted. Our working user.js file is User.js

2022-05-19 22:06 UTC, megschuetz commented on src/Activity.js
> +    // const userData = this.findUser(userId);
Probably just remove line 28 here.

2022-05-20 00:47 UTC, ameliaeiger approved these changes

2022-05-20 00:47 UTC, merged